In [141]:
import numpy as np

In [142]:
lst = list(range(1,30))
arr1 = np.array(lst)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [143]:
arr2 = np.arange(1,30)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [144]:
arr3 = np.array([1,2,3,4,5,6,7,8,9,12,3,4,4,3])
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 12,  3,  4,  4,  3])

In [145]:
arr4 = np.zeros((10))
arr4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [146]:
arr5 = np.ones((10))
arr5

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [147]:
arr6 = np.zeros((5,10))
arr6

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [148]:
arr7 = np.linspace(1,10,20)
arr7

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [149]:
arr= np.arange(0,30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [150]:
arr8 = np.arange(0,30).reshape(10,3)
arr8

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

## random numbers array gen

In [151]:
arr_1d = np.random.randint(1,5,9)
arr_1d

array([2, 4, 3, 2, 2, 4, 3, 3, 3])

In [152]:
arr_2d = np.random.randint(1,5,(5,2))
arr_2d

array([[1, 4],
       [3, 2],
       [3, 3],
       [3, 2],
       [1, 1]])

In [153]:
arr_3d = np.random.random(10)
arr_3d


array([0.41869638, 0.16310286, 0.13902034, 0.28576862, 0.51610437,
       0.58223245, 0.97203759, 0.06309754, 0.25975624, 0.63623986])

In [154]:
arr_4D = np.random.random((5,10))
arr_4D

array([[0.97053056, 0.97257562, 0.83143203, 0.90853761, 0.68640961,
        0.13893537, 0.19691318, 0.72924716, 0.36860922, 0.44846762],
       [0.97931723, 0.78141387, 0.75355791, 0.94965154, 0.56211053,
        0.48816298, 0.61911361, 0.10114711, 0.64215652, 0.47251483],
       [0.38746399, 0.98277404, 0.28446146, 0.26585973, 0.76644881,
        0.29737899, 0.70983859, 0.84590133, 0.75947749, 0.03296267],
       [0.59797451, 0.53001264, 0.60679374, 0.29542813, 0.26982698,
        0.30214224, 0.57072976, 0.98437208, 0.96724294, 0.22483689],
       [0.81217156, 0.41989649, 0.6223202 , 0.98466637, 0.03975278,
        0.10276393, 0.54675731, 0.6372326 , 0.95720181, 0.56243805]])

### Array Attributes

In [155]:
arr = np.arange(0,60).reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [156]:
arr.shape

(12, 5)

In [157]:
arr.dtype

dtype('int32')

In [158]:
arr.ndim

2

In [159]:
arr.size

60

In [160]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [161]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [162]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [163]:
list_2d = [[1,2,3],[4,5,6]]
list_2d

[[1, 2, 3], [4, 5, 6]]

In [164]:
arr = np.array(list_2d)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [165]:
arr.shape

(2, 3)

In [166]:
arr.T.shape

(3, 2)

### Accessing elements from 1D and 2D array

for 1d array
[row_start:end:step/skip]

for 2d array
[row-start:end:skip/step,column_start:end:skip/step]

In [167]:
arr = np.arange(60)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [168]:
arr[15]

15

In [169]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [170]:
arr[0:20:2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [171]:
## 2d array
arr = np.arange(60).reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [172]:
arr[1]

array([5, 6, 7, 8, 9])

In [173]:
arr[1,1]

6

In [174]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [175]:
arr[0:5,1:2]

array([[ 1],
       [ 6],
       [11],
       [16],
       [21]])

In [176]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [177]:
arr[1,3:5]

array([8, 9])

In [178]:
arr[7:8,4][0] = 100

In [179]:
arr

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38, 100],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59]])

In [180]:
arr[11][-1]

59

In [181]:
arr[-1][-1]

59

In [182]:
arr[-1,-1]

59

In [183]:
arr[11:,-1][0]

59

In [184]:
arr[11,4]

59

### for 3d array

In [185]:
arr = np.array(np.arange(225).reshape(5,15,3))
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [186]:
arr.shape
#5 --> table
#15 -->row
#3 --> columns
###[table,row,col]     --> for 3d array

(5, 15, 3)

In [187]:
arr = np.arange(60).reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [188]:
np.min(arr)

0

In [189]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [190]:
arr[0][2:]

array([2, 3, 4])

In [191]:
# arr[:,0,:]

In [206]:
# arr[:,0:1,0:1]

In [207]:
arr[2]

array([10, 11, 12, 13, 14])

In [208]:
# arr[2][3][1] = 100

In [209]:
arr[0]

array([0, 1, 2, 3, 4])

In [210]:
arr[0][::-1]

array([4, 3, 2, 1, 0])

In [211]:
# arr[0][::-1,::-1]

### Sorting in Array

In [212]:
arr1 = np.array([2,4,45,7,2,4,3])
arr2 = np.array([[0,5,6,3,1],[3,2,5,3,2]])

In [213]:
arr1.sort()
arr1

array([ 2,  2,  3,  4,  4,  7, 45])

In [214]:
arr1[::-1]

array([45,  7,  4,  4,  3,  2,  2])

In [215]:
arr2.sort()
arr2

array([[0, 1, 3, 5, 6],
       [2, 2, 3, 3, 5]])

In [216]:
arr2[::-1,::-1]

array([[5, 3, 3, 2, 2],
       [6, 5, 3, 1, 0]])

### argsort()

In [217]:
arr1 = np.array([7,5,9])
arr1

array([7, 5, 9])

In [218]:
arr1.argsort()         ## it returns sorted index

array([1, 0, 2], dtype=int64)

In [219]:
np.argsort(arr1)

array([1, 0, 2], dtype=int64)

In [221]:
arr2 = np.array([[0,5,6,3,1],[3,2,5,3,2]])
arr2

array([[0, 5, 6, 3, 1],
       [3, 2, 5, 3, 2]])

In [222]:
np.argsort(arr2)

array([[0, 4, 3, 1, 2],
       [1, 4, 0, 3, 2]], dtype=int64)

### Arithematical operations 


In [230]:
a = [1,2,3,4,5,6,7,8,9]
b = [2,3,4,5,6,7,8,9,0]
arr1 = np.array(a)
arr2 = np.array(b)


In [229]:
arr1*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18,  6])

In [231]:
arr1*arr2

array([ 2,  6, 12, 20, 30, 42, 56, 72,  0])

In [232]:
### concatenate

np.concatenate([arr1,arr2])

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 2, 3, 4, 5, 6, 7, 8, 9, 0])

### some more functions

In [233]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
vstacked = np.vstack((array1,array2))     #vstack
vstacked

array([[1, 2, 3],
       [4, 5, 6]])

In [234]:
hstacked = np.hstack((array1,array2))
hstacked

array([1, 2, 3, 4, 5, 6])

In [235]:
array = np.array([1, 2, 3, 4, 5, 6])
array

array([1, 2, 3, 4, 5, 6])

In [242]:
splited_array = np.split(array,3)
splited_array

[array([1, 2]), array([3, 4]), array([5, 6])]

In [244]:
array = np.array([[1,2,3,4],[5,6,7,8]])
array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [246]:
hrsplit_arr = np.hsplit(array,2)
hrsplit_arr

[array([[1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8]])]

In [250]:


vtsplit = np.vsplit(array,2)
vtsplit

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]