In [1]:
import numpy as np

In [2]:
lst = list(range(1,30))
arr1 = np.array(lst)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [3]:
arr2 = np.arange(1,30)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [4]:
arr3 = np.array([1,2,3,4,5,6,7,8,9,12,3,4,4,3])
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 12,  3,  4,  4,  3])

In [5]:
arr4 = np.zeros((10))
arr4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
arr5 = np.ones((10))
arr5

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
arr6 = np.zeros((5,10))
arr6

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [80]:
arr7 = np.linspace(1,10,15)
arr7

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])

In [9]:
arr= np.arange(0,30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [10]:
arr8 = np.arange(0,30).reshape(10,3)
arr8

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

## random numbers array gen

In [11]:
arr_1d = np.random.randint(1,5,9)
arr_1d

array([4, 3, 3, 1, 2, 3, 1, 3, 4])

In [12]:
arr_2d = np.random.randint(1,5,(5,2))
arr_2d

array([[1, 3],
       [2, 1],
       [3, 2],
       [3, 3],
       [2, 4]])

In [82]:
arr_3d = np.random.random(10)
arr_3d


array([0.19208635, 0.13407038, 0.34829484, 0.45078044, 0.02999843,
       0.11218429, 0.27899052, 0.30712666, 0.02416982, 0.94432512])

In [14]:
arr_4D = np.random.random((5,10))
arr_4D

array([[0.92182538, 0.83354242, 0.76112557, 0.721071  , 0.77007686,
        0.50794152, 0.43277937, 0.93186293, 0.49354813, 0.95351642],
       [0.69131903, 0.7849388 , 0.51010725, 0.39415431, 0.46884588,
        0.25984741, 0.64420078, 0.07858718, 0.99538812, 0.44349123],
       [0.2939426 , 0.33221407, 0.55223338, 0.34233438, 0.94769886,
        0.71073623, 0.49187632, 0.54924829, 0.2616865 , 0.32804014],
       [0.93455238, 0.64849462, 0.54096814, 0.06517523, 0.46844793,
        0.75200579, 0.46214367, 0.08926723, 0.11520292, 0.09284552],
       [0.87920516, 0.43568314, 0.28356968, 0.12459896, 0.30389398,
        0.14302383, 0.00713908, 0.83084685, 0.95268647, 0.31499628]])

### Array Attributes

In [15]:
arr = np.arange(0,60).reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [16]:
arr.shape

(12, 5)

In [17]:
arr.dtype

dtype('int32')

In [18]:
arr.ndim

2

In [19]:
arr.size

60

In [20]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [21]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [22]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [23]:
list_2d = [[1,2,3],[4,5,6]]
list_2d

[[1, 2, 3], [4, 5, 6]]

In [24]:
arr = np.array(list_2d)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
arr.shape

(2, 3)

In [84]:
arr.T.shape

(5, 12)

### Accessing elements from 1D and 2D array

for 1d array
[row_start:end:step/skip]

for 2d array
[row-start:end:skip/step,column_start:end:skip/step]

In [27]:
arr = np.arange(60)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [28]:
arr[15]

15

In [29]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [30]:
arr[0:20:2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [31]:
## 2d array
arr = np.arange(60).reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [32]:
arr[1]

array([5, 6, 7, 8, 9])

In [33]:
arr[1,1]

6

In [34]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [35]:
arr[0:5,1:2]

array([[ 1],
       [ 6],
       [11],
       [16],
       [21]])

In [36]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [37]:
arr[1,3:5]

array([8, 9])

In [88]:
arr[7:8,4][0] =100

In [85]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [39]:
arr

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38, 100],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59]])

In [40]:
arr[11][-1]

59

In [41]:
arr[-1][-1]

59

In [42]:
arr[-1,-1]

59

In [43]:
arr[11:,-1][0]

59

In [44]:
arr[11,4]

59

### for 3d array

In [89]:
arr12 = np.array(np.arange(225).reshape(5,15,3))
arr12

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [46]:
arr.shape
#5 --> table
#15 -->row
#3 --> columns
###[table,row,col]     --> for 3d array

(5, 15, 3)

In [47]:
arr = np.arange(60).reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [48]:
np.min(arr) 
## MAX ,STD,MEAN,

0

In [49]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [91]:
arr12[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [93]:
arr12[0][2:]

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [96]:
arr12[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [94]:
arr12[:,0,:]

array([[  0,   1,   2],
       [ 45,  46,  47],
       [ 90,  91,  92],
       [135, 136, 137],
       [180, 181, 182]])

In [97]:
arr12[:,0:1,0:1]

array([[[  0]],

       [[ 45]],

       [[ 90]],

       [[135]],

       [[180]]])

In [53]:
arr[2]

array([10, 11, 12, 13, 14])

In [54]:
# arr[2][3][1] = 100

In [55]:
arr[0]

array([0, 1, 2, 3, 4])

In [56]:
arr[0][::-1]

array([4, 3, 2, 1, 0])

In [100]:
arr12[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [102]:
arr12[0][::-1,::-1]

array([[44, 43, 42],
       [41, 40, 39],
       [38, 37, 36],
       [35, 34, 33],
       [32, 31, 30],
       [29, 28, 27],
       [26, 25, 24],
       [23, 22, 21],
       [20, 19, 18],
       [17, 16, 15],
       [14, 13, 12],
       [11, 10,  9],
       [ 8,  7,  6],
       [ 5,  4,  3],
       [ 2,  1,  0]])

### Sorting in Array

In [58]:
arr1 = np.array([2,4,45,7,2,4,3])
arr2 = np.array([[0,5,6,3,1],[3,2,5,3,2]])

In [59]:
arr1.sort()
arr1

array([ 2,  2,  3,  4,  4,  7, 45])

In [60]:
arr1[::-1]

array([45,  7,  4,  4,  3,  2,  2])

In [61]:
arr2.sort()
arr2

array([[0, 1, 3, 5, 6],
       [2, 2, 3, 3, 5]])

In [62]:
arr2[::-1,::-1]

array([[5, 3, 3, 2, 2],
       [6, 5, 3, 1, 0]])

### argsort()

In [63]:
arr1 = np.array([7,5,9])
arr1

array([7, 5, 9])

In [64]:
arr1.argsort()         ## it returns sorted index

array([1, 0, 2], dtype=int64)

In [65]:
np.argsort(arr1)

array([1, 0, 2], dtype=int64)

In [66]:
arr2 = np.array([[0,5,6,3,1],[3,2,5,3,2]])
arr2

array([[0, 5, 6, 3, 1],
       [3, 2, 5, 3, 2]])

In [67]:
np.argsort(arr2)

array([[0, 4, 3, 1, 2],
       [1, 4, 0, 3, 2]], dtype=int64)

### Arithematical operations 


In [105]:
a = [1,2,3,4,5,6,7,8,9]
b = [2,3,4,5,6,7,8,9,0]
arr1 = np.array(a)
arr2 = np.array(b)


In [69]:
arr1*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [106]:
arr1*arr2

array([ 2,  6, 12, 20, 30, 42, 56, 72,  0])

In [71]:
### concatenate

np.concatenate([arr1,arr2])

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 2, 3, 4, 5, 6, 7, 8, 9, 0])

### some more functions

In [72]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
vstacked = np.vstack((array1,array2))     #vstack
vstacked

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
hstacked = np.hstack((array1,array2))
hstacked

array([1, 2, 3, 4, 5, 6])

In [74]:
array = np.array([1, 2, 3, 4, 5, 6])
array

array([1, 2, 3, 4, 5, 6])

In [75]:
splited_array = np.split(array,3)
splited_array

[array([1, 2]), array([3, 4]), array([5, 6])]

In [76]:
array = np.array([[1,2,3,4],[5,6,7,8]])
array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [77]:
hrsplit_arr = np.hsplit(array,2)
hrsplit_arr

[array([[1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8]])]

In [78]:


vtsplit = np.vsplit(array,2)
vtsplit

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]

In [ ]:
#  Write a NumPy program to create an array of all even integers from 30 to 70.
# Question : Create a 3×3 numpy array of all True’s
# Question : Extract all odd numbers from array
# input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# output: array([1, 3, 5, 7, 9])
# Question: Replace all odd numbers in arr with -1
# input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# output: array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
# Question: Get the common items between a and b

# Input: a = np.array([1,2,3,2,3,4,3,4,5,6])
#        b = np.array([7,2,10,2,7,4,9,4,9,8])

# Output: array([2, 4])